### ISSUE TITLE
v280 login failed

### ISSUE THREAD

**Issue by ladyhyena** [Awbz/OneLife#116]
I keep getting the login failed whenever I try to play my server. I did the runServer with admin first and added my login details checked that I got it right but no luck joining. Please help.

**Comment by Awbz** [comment]
I just tested myself and this still seems to be working as expected, so I suspect that there might be something slightly off with your setup.  The default settings don't require any credentials, as the *requireTicketServerCheck.ini* is set to 0, but that could also cause login issues if yours is enabled.  Does it work if you remove the email address or key info?

Are you sure that you have "Use custom server" checked in the game's settings, and that it's pointing to the "localhost" address?

You'll want to connect to **localhost** if you're attempting to connect from the same PC that you're running the server.  Otherwise, you'd need the hostname or IP of the server PC.  Also, if you're trying to connect to a remote server, you'd also have to make sure that port 8005 is forwarded appropriately.

**Comment by ladyhyena** [comment]
the last version didn't work until I put in my stuff so I thought I had to but it fails with or without. I'm trying to connect to the local server and it is ticked in settings and 8005 is the port.  I'm sure its something simple that I'm doing wrong. It was the win full I was supposed to extract and use right? Thankyou for getting back to me.

**Comment by ladyhyena** [comment]
figured it out

**Comment by ladyhyena** [comment]
Having the onelifeserver app open with the onelife+ did make it work but now everytime I try to open the onelifeserver it closes too fast for me to even look at the code. And because it won't stay open I can't get back on my server.

**Comment by Awbz** [comment]
Hmm, first let's make sure that the symbolic links were created with the runServer.bat file.  If these symlinks exist, then you're fine to run OneLifeServer.exe directly.  Your folder structure should look something like this, take note of the folder icons with symlink arrows:

![serversymlinks](https://user-images.githubusercontent.com/24634429/52581629-0f0dd600-2de0-11e9-8fa9-e2571ce65f5d.png)

Next, it sounds like you're just double-clicking the OneLifeServer.exe file.  If you open Command Prompt and then launch runServer.bat (or OneLifeServer.exe) through the terminal, that will let you see any messages it might print out instead of immediately closing.

Are you certain that an existing server instance isn't already running?  If you have a previous instance still running, you can halt it gracefully by pressing CTRL-C on the server's terminal window.  Or you should be able to just launch your client and connect to it, as there's no need to re-launch the server unless you've previously shut it down.

**Comment by ladyhyena** [comment]
All the folders look the same except I have a mapchangelogs added.  I'm certain I shut down the server after closing the game but I checked task manager to make sure and it was. I took screen shots of the exe and bat code.
![serverbat](https://user-images.githubusercontent.com/57371784/68630689-fdc53780-04df-11ea-9c71-989041892c3e.png)
![serverexe](https://user-images.githubusercontent.com/57371784/68630690-fe5dce00-04df-11ea-8498-bd7acb4bce46.png)

**Comment by Awbz** [comment]
Can you try deleting all of the *.db files in the server folder?  This will effectively wipe your server and start it fresh, or does it still work if you run it as admin?

I'm going to guess that there's a permissions issue of some sort, likely due to the files being created while first running as administrator and then subsequently launching it as a normal user.  If it works properly when running as admin, that would help confirm the case.

**Comment by ladyhyena** [comment]
I deleted the eve.db file the only one I could find but opening onelifeserver.exe just made a new one before closing straight away and running the game without opening server led to connection failed. running with or without admin doesn't seem to change this. Do you think it could be because I changed settings after first running the server?

**Comment by Awbz** [comment]
Changing settings after you've launched the server should be fine, only they obviously won't take effect until the server has been restarted.  However, there's always the possibility?  Can you let me know which settings you changed and I can try to replicate the issue?

**Comment by ladyhyena** [comment]
lifespanmultiplier to 3, maxtoolslotsperplayer to 40, minfooddecrementseconds to 6
I'm going to try installing again. I download the win full zip. I extract to a safe place, in server file runSerer.bat pressed any button to close then run onelife+.exe make sure custom server is ticked and that its the localhost. Connection failure quit try opening onelifeserver which blinks in and out. Huh this time there's a map.db

**Comment by Awbz** [comment]
Just to be clear, are you launching **runServer.bat** as an administrator and then leaving the terminal window open?  The terminal window shouldn't prompt you to press any button to close it unless something went wrong or if it was shut down.  You shouldn't need to launch the game client with elevated permissions at all.

I tested with your settings and everything seems fine, so I think we can rule your setting changes out.

**Comment by ladyhyena** [comment]
Yeah I a small brain. I was closing the runserver.bat once I thought it was finished making the needed files.

**Comment by Awbz** [comment]
That's ok!  It can be a little confusing, but yes...that terminal window *is* the server.  So you'll need to make sure that window stays open as long as you want to be able to connect to it.

The runServer.bat file creates the necessary symbolic links to the data folders and then immediately runs OneLifeServer.exe.  The symlinks are only there so you don't have to have duplicate copies of the data folders for both your client and the server itself.

At any rate, your server terminal window should look something like the following and be waiting for client connections:
![serverexample](https://user-images.githubusercontent.com/24634429/68635094-4d8a0b80-04ac-11ea-8ab0-c79b0494e9ee.png)

From that point, you should be able to connect to your server (with any client you prefer) on the port specified.

**Comment by ladyhyena** [comment]
Yep works fine now, thankyou for all your help.
