### ISSUE TITLE
typing adds an "s" when trying to talk

### ISSUE THREAD

**Issue by tana-OHOL** [Awbz/OneLife#12]
everytime I try to talk, if I type "HELLO" for example, it will always type "HS ELLO"
so basically it types the first letter that I type, adds an "s" and a space then resumes typing what I wrote
I tried with the vanilla client and it doesn't do it, so I guess it's a mod problem. I just downloaded the last version.

**Comment by Awbz** [comment]
Spoke with Tana about this on Twitch and after she tried again, the extra "S" disappeared but she still seemed to have an extra space after the first character typed...but only when using the quick-chat and not after pressing Enter first to chat.  I was unable to reproduce this myself and multiple other users also had no similar issue.

Suspect that this could be related to international keyboards (she uses an AZERTY layout) and/or older operating systems, as none of the quick-chat code has changed since its implementation and Tana never had this issue with previous versions.

Leaving this open for the time being.

**Comment by Awbz** [comment]
Side note - I tested a new build method with this last release that compiles client binaries for all 3 platforms from Linux.  Perhaps something in my build environment changed that might have caused this?  If the issue persists with the next release, will build from my previous setup and see if that clears the issue up or not.

**Comment by Awbz** [comment]
Confirmed with Tana that this no longer appears to be an issue for her after the yesterday's update for the Steam release.
