### ISSUE TITLE
renewing home marker causes crashing

### ISSUE THREAD

**Issue by ladyhyena** [Awbz/OneLife#126]
HI when I take down the non functioning home marker then put it up again as soon as I walk away the game crashes then starves me to death before I can reconnect. I tested this twice and both times it crashed.

**Comment by Awbz** [comment]
This was due to a bad release that I'd put up for about the first hour, so you were likely one of the 30-ish people who downloaded it quickly.  I've since removed that version and put up a good/working version that shouldn't crash related to homemarkers.

If you've re-downloaded the mod and it is still having crashing problems, please re-open this issue and I'll take a look into it!  My apologies for the confusion.
