### ISSUE TITLE
Update Private Server?

### ISSUE THREAD

**Issue by elddire** [Awbz/OneLife#147]
Hopefully this is ok the post here, as I haven't been able to find answers anywhere else. If not I'll remove it upon request. 

I've been using this client to host my own private server. I've updated the mod itself before for the base game, but I tried updating my private server for the first time the other day to find that it wont work anymore. The (private) server runs fine using the un-modded client, but as soon as I try to run OneLife+.exe, this message comes up: 
![image](https://user-images.githubusercontent.com/64285196/80255620-2b3b1300-8632-11ea-96ac-5998b001a8b6.png)
I also tried running the server off of my IP so I could play it on another computer and the when I tried logging in it says theres a "version mismatch". 

Obviously there was an issue with my trying to update, but I'm not sure what I did wrong or even, how I was supposed to properly update the game. Any help would be greatly appreciated!

Thanks.

**Comment by Awbz** [comment]
The most up-to-date server binary, compiled for Windows, is always available in the "win_full" packages that I release.  These "full" releases contain the entire game in a ready-to-play state, meaning you shouldn't have to do any auto-updating because each release should contain everything you need up to that particular revision.  If you were to launch the OneLife+.exe (or the unmodified OneLife.exe) client that resides inside the "win_full" package, it should always be at the currently available version...which is client/server v330 & data v331 at the time of this post.

Technically, this means that all you should have to do in order to update your server is to download the most current "win_full" package and extract the contents into your existing server folder while overwriting any merge conflicts.  The only drawback with this method is that it doesn't remove files that were possibly meant to be deleted...like if a transition was removed, etc.  You typically can't just replace OneLifeServer.exe with a new version because other files, such as the data/content files, also need to be updated.

That being said, your best bet when updating your server to a new version would be to extract the current "win_full" package into a new/separate location before manually transferring your previous instance's files into this new location.  This also ensures that if things happen to go wrong, you won't have polluted your previously working setup.

The files/folders from the **server** folder that you'd want to backup/transfer are:

* curseLog (folder & contents)
* failureLog (folder & contents)
* foodLog (folder & contents)
* lifeLog (folder & contents)
* mapChangeLogs (folder & contents)
* settings (folder & contents - only if you've customized any server settings and don't want to re-do them)
* All *.db files:
   * biome.db
   * curseCount.db
   * curses.db
   * eve.db
   * floor.db
   * floorTime.db
   * grave.db
   * lookTime.db
   * map.db
   * mapTime.db
   * meta.db
   * playerStats.db
* biomeRandSeed.txt
* familyDataLog.txt
* log.txt
* recentPlacements.txt

It would probably be a good idea to also backup these files on a regular basis if you're concerned about losing any progress you've made.  Creating a backup of these files would also make it simpler to transfer your progression to any future version(s).

Also, remember to gracefully shutdown the server (with CTRL+C) to allow changes to be saved and to launch the server using the runServer.bat file (in order to create the necessary symlinks to the data files/folders.)  If the symlinks aren't created, you'll need to launch runServer.bat as an Administrator or enable Developer Mode in Windows 10.  Hope this helps!

**Comment by elddire** [comment]
Oh my gosh. I did not expect an answer, let alone something so thorough. This was exactly the answer I was looking for. Thank you so much for taking the time to respond! Really appreciate it.

**Comment by elddire** [comment]
Ok, so. I have no idea what I did wrong, but when I logged back into the server the world was essentially reset EXCEPT for one thing.

**Comment by Spodnie** [comment]
If you didn't log too long it could reset. Chunks in game that aren't visited by players get reset after a few days I believe (not sure exactly after how long)
I have no idea why your floors didn't reset tho.

**Comment by elddire** [comment]
I don't think that's the case, since it only happened after I updated, and I played on it earlier that day anyway.

**Comment by Awbz** [comment]
It's very possible that starting the server in an incorrect state could've wiped out your changes, and then subsequently saved your world in an undesirable state.  Shutting down the server improperly (not using CTRL+C) could also cause changes not to be saved, which can happen if you simple click the "X" to close the terminal window.

You could also try copying over your previous **mapDummyRecall.txt** file and restarting the server to see if that happens to restore anything.  Are you 100% certain that you copied all of the necessary files?  This sounds like your **map.db** file wasn't copied over, or became corrupted somehow.  To touch on the point raised by @Spodnie, the **mapTime.db** file contains timestamps of "last seen" items, which the game will cull after 7 days (default setting, defined in mapCellForgottenSeconds.txt) of not being seen, so make sure that file was copied over as well!

If you're certain that you copied all of the proper files over, then you could check to see if you can grab these files from before your upgrade attempt.  **If** you have [Previous Versions](https://winaero.com/blog/restore-previous-versions-windows-10/) enabled in Windows, you should be able to right-click the old server folder and select the Previous Versions tab in the Properties window for that directory.  This would allow you to "go back in time" to any available date and grab the files you need before they became cattywompus.

In the event that you didn't have Previous Versions enabled and don't have access to your old/working map, your only recourse at that point might be setting yourself up with VOG mode and using the powers of "God" to spawn in things.  Only you'd have to use a non-modified client, as one of the features in the OneLife+ mod doesn't play nicely with the VOG mode keybinds (yet.)

But hopefully it's just a matter of you forgetting to copy over your map.db file.  Otherwise, I don't know if there's much else I could do to help.

**Comment by elddire** [comment]
Yup. I definitely missed the map.db file. I probably went over the backed up files ten times and didn't notice it.
I checked the server after adding in the missing file and it all seems to be working properly, so thank you, again!
