### ISSUE TITLE
Version 363 Windows server?

### ISSUE THREAD

**Issue by TheFatherOfTime** [Awbz/OneLife#163]
Outdated server. Latest one i could find was 361.

**Comment by elddire** [comment]
I'm trying to run a private server and I'm having the same issue. Any word on whether it will be updated?

**Comment by TheFatherOfTime** [comment]
No word yet... :(

**Comment by Awbz** [comment]
I normally only push releases when Jason pushes out a new ***client*** binary, so the changes he's made (mostly to the server side of things) since last September had not been merged until today's update.  I apologize for the long delay on this, but today's release should catch things up with the official servers at Data Version 363 and Client/Server Version at 364.

**Comment by Awbz** [comment]
It also appears that Jason has done some work towards getting an official Windows server build put up on Steam, hopefully available sometime soon.  Once that is the case, the server builds I release will no longer be needed.
