### ISSUE TITLE
Add an option to adjust FOV with mouse wheel

### ISSUE THREAD

**Issue by ShaunDreclin** [Awbz/OneLife#22]
Using the left and right arrows to zoom in and out is kind of confusing, mouse wheel would be much simpler

**Comment by Awbz** [comment]
This option has been requested multiple times, but 99% of users have programmable mouse buttons that they're able to use in the meantime.  Jason does not currently map the mouse wheel, so I'd have to do that in his minorGems project where the framework code lives.

Up until now, I've only had to make code changes in the OneLife project (which is why I haven't just added it in yet.)  This will likely be added sometime in the near future, after I work out the kinks on the various other features.

For whatever it's worth - Jason has the code split into 3 projects.  minorGems (framework), OneLife (client/server/editor), and OneLifeData7 (content.)

**Comment by ShaunDreclin** [comment]
Oh I didn't even think of just remapping my mouse wheel! That'll get the job done for now
