### ISSUE TITLE
Mod outdated

### ISSUE THREAD

**Issue by pfgithub** [Awbz/OneLife#25]
172 is the latest version on [the latest release page](https://github.com/Awbz/OneLife/releases/latest), but the mod says it is outdated and expecting version 174

**Comment by Awbz** [comment]
When Jason releases a new client version, it's typically followed up by a new data (content) version shortly thereafter.  Generally, I like to wait until he has the full update released "to the wild" before uploading an updated version of the mod.

This is mostly due to people accidentally grabbing the modded client early, but fear not!  I try to keep my updates within an hour of the vanilla game.

**Comment by Awbz** [comment]
No apologies needed!  The wording on that messaging *is* a bit confusing if there's no updated version of the mod waiting for you.  Typically this only happens to the "eager beavers" that update early (maybe even before the servers are done restarting) but it might be something I make more elegant in the future.

Right now the mod checks its own hard-coded version against the version number that appears in your binary.txt file.  The binary.txt file generally only gets updated when Jason pushes a new official client update, so that's the version number being displayed for "expected" and not necessarily which version of the mod is expected.  But I currently don't have anything checking to see if the number in binary.txt is available on the latest releases page yet or not.

Sorry for the confusion!  (And I'm sure you've noticed that an updated version has since been made available.)
