### ISSUE TITLE
Login Failed Trying to Join Local Server

### ISSUE THREAD

**Issue by Cellispere** [Awbz/OneLife#58]
Hiya, I've been trying for two to three days now to get a private server to work and I found your package here, it looks amazing! The problem is though, I just can't log in. Server seems to start up fine but the moment I try to join it, the server "crashes" as in it doesn't even leave an error message. It's very weird, so I will copy/paste some of the log.txt here.

L4 | Sat Feb 09 16:39:06 2019 (178 ms) | general | Server starting up
L4 | Sat Feb 09 16:39:06 2019 (178 ms) | general | Server using version number 198
L4 | Sat Feb 09 16:39:06 2019 (192 ms) | general | curseLog starting up
L4 | Sat Feb 09 16:39:06 2019 (193 ms) | general | lifeLog starting up
L4 | Sat Feb 09 16:39:06 2019 (196 ms) | general | foodLog starting up
L4 | Sat Feb 09 16:39:06 2019 (196 ms) | general | failureLog starting up
L4 | Sat Feb 09 16:39:06 2019 (210 ms) | general | No lookTimes present, not cleaning map.db
L4 | Sat Feb 09 16:39:06 2019 (212 ms) | general | No lookTimes present, not cleaning mapTime.db
L4 | Sat Feb 09 16:39:06 2019 (214 ms) | general | No lookTimes present, not cleaning biome.db
L4 | Sat Feb 09 16:39:06 2019 (217 ms) | general | No lookTimes present, not cleaning floor.db
L4 | Sat Feb 09 16:39:06 2019 (219 ms) | general | No lookTimes present, not cleaning floorTime.db
L4 | Sat Feb 09 16:39:06 2019 (223 ms) | general | MetadataDB:  Found 0 records with max MetadataID of 0
L4 | Sat Feb 09 16:39:06 2019 (223 ms) | general | 
Cleaning map of objects that have been removed...
L4 | Sat Feb 09 16:39:06 2019 (223 ms) | general | ...0 map cells were set, and 0 needed to be cleared.
L4 | Sat Feb 09 16:39:06 2019 (224 ms) | general | ...0 contained objects present, and 0 needed to be cleared.
L4 | Sat Feb 09 16:39:06 2019 (224 ms) | general | ...0 database records total (0 max hash bin depth).
L4 | Sat Feb 09 16:39:06 2019 (255 ms) | general | Listening for connection on port 8005
L4 | Sat Feb 09 16:56:49 2019 (269 ms) | general | Got connection from 127.0.0.1:1066
L4 | Sat Feb 09 16:56:49 2019 (282 ms) | general | Listening for another connection on port 8005
L4 | Sat Feb 09 16:56:50 2019 (740 ms) | general | Got new player logged in

After the last line, the server instantly shuts down and the game pops up with a " Login Failed". I should mention there is another line that appears right after the last line in the server command prompt window that doesn't show up in the log, "Placing new Eve:  Placing new Eve: trying radius of 50 from camp"". I've only managed to quickly catch this line through screenshotting my desktop. 

I'm so confused by this and the lack of an error to go by, would it be possible if you could help me?

I am using the email and key I got when I bought the game from steam, if that's of any consequence, and I'm also using the OHOL+_v198_win_full.zip (saved in a different location from the steam version of the game)

**Comment by Awbz** [comment]
The most common cause of this is missing data in the server folder.  If you use the "runServer.bat" file included in the "win_full" package, it should attempt to create the necessary symbolic links to the data folders for you.  Alternatively, however less preferred, you can copy the needed folders into the server sub-folder and that should clear things up!

In my testing, you'll need to use this batch file (to create the symlinks) at least once as an administrator - unless you've got Developer Mode enabled on Windows 10.

**Comment by Cellispere** [comment]
It's probably excessive but I had been using the runServer.bat file every time I launched the server, still no luck. I'm unsure if it's vital info,  but after running the file as admin all it does is flicker quickly, rather than staying and running a program. not sure if that's typical for .bat files

**Comment by Awbz** [comment]
Odd, I could've swore that I checked that file before uploading...but it turns out that this step was skipped during my build process!  I'll try to make sure it's resolved permanently for future builds, so thanks for letting me know that it's happened again and my apologies on the mistake.

Here is what the contents of the batch file should look like.  Please edit yours to match until I get the fixed release(s) out there:
```
@echo off
cd /d %~dp0

echo "Creating symlinks..."

mklink /D categories ..\categories
mklink /D objects ..\objects
mklink /D transitions ..\transitions
mklink /D tutorialMaps ..\tutorialMaps
mklink dataVersionNumber.txt ..\dataVersionNumber.txt

echo "Starting server..."

OneLifeServer

pause
```

**Comment by Cellispere** [comment]
Unfortunately, that seems to be the same code that was already in the batch file that I have. For the sake of testing, I copy and pasted it to the .bat anyway, but as expected, it still doesn't seem to be functioning properly

**Comment by Awbz** [comment]
Hmm.  I just re-tested it on my own PC and the only other thing that my build process missed was changing some of the server's settings to "nicer" defaults for private servers - such as setting **requireTicketServer.ini** to **0** instead of 1.  Can you make sure that's also set to 0 in your settings folder?

Out of curiosity, are you attempting to run the server from an external drive?  I believe there could be issues when trying to create symlinks on removable media.  Also please check the attached image to make sure your server folder looks similar after launching via the .bat file.

![serversymlinks](https://user-images.githubusercontent.com/24634429/52581629-0f0dd600-2de0-11e9-8fa9-e2571ce65f5d.png)

Note the following are symlinked (but could be copied instead):

**..\categories
..\objects
..\transitions
..\tutorialMaps
dataVersionNumber.txt**

**Comment by Cellispere** [comment]
!!!! OMG! My server folder looked nothing like yours, so I copied those folders, and it works! AHH! I'm so happy! Thank you so so much for your time and patience!

**Comment by Awbz** [comment]
Fantastic!  Although, I'm curious now as to why the symbolic linking didn't work, especially if you were running it as an administrator.  The only other thing that comes to mind is the external drive/removable media thing.  At any rate, I'm glad to hear that you got things working and happy to help out!
