### ISSUE TITLE
Version Mismatch when running windows server

### ISSUE THREAD

**Issue by Psykout88** [Awbz/OneLife#73]
On the newest release, the server and client in the Windows Full release don't appear to be the same version. When launching the server and then launching either client from same directory, there is a mismatch from 213 to 212.

**Comment by Awbz** [comment]
Did you use the runServer.bat file to create the necessary symlinks for the server?  If your server is reporting that it's v212 still, then that's likely the culprit.

**Comment by Psykout88** [comment]
Ahh needed to run the batch as administrator, good to go. Any news on VOG commands using the modded client? Still unable to access due to auto chat kicking in and blocking shift commands going thru.

**Comment by Awbz** [comment]
Your server folder structure should look something like the image in this https://github.com/Awbz/OneLife/issues/58#issuecomment-462419728 

If you don't have Developer Mode enabled on Windows 10, then you may need to run the batch file as an administrator (at least the first time) in order to create the symlinks.

**Comment by Awbz** [comment]
Excellent!  As far as VOG mode goes, yes, the next release will have better support.  Among other QoL updates.  👍

**Comment by Psykout88** [comment]
Hmm server is not holding objects or walls in between restarts and floors are still not adhering, user error?

**Comment by Awbz** [comment]
The code has been committed, but I haven't uploaded a public release to Github yet.  However, I did make sure to test it thoroughly to ensure it was working as expected.  I typically don't like to release "out of band" or "point" releases, plus I'm still in the middle of making a bunch of other changes, so unless you build it from source yourself ... you won't see those actual changes until the next release.

For what it's worth, on the releases page you can see a link of commits that have been made since that release.  That will let you know which changes aren't yet in that particular release.  Sorry about the confusion that the auto-closing commit messages caused!
