### ISSUE TITLE
Add docs for implementation of server webpages.

### ISSUE THREAD

**Issue by Adrinus** [Awbz/OneLife#91]
It'd be great to see how the built-in webViewer functionality was meant to be implemented. Perhaps my understanding is too rudimentary to figure it out: all the more reason some reference to a "Quick Setup" of the server pages.(lineage etc.)

**Comment by Awbz** [comment]
This is really beyond the scope of this particular project, but I can help point you in the right direction for this!  Jason currently has no official support for self-hosted servers, but he does have some [documentation](https://github.com/jasonrohrer/OneLife/tree/master/documentation/devProcess) on the subject, and you'll want to make sure you have the [appropriate pre-requisite packages](https://github.com/jasonrohrer/OneLife/blob/master/documentation/devProcess/webServerPackages.txt) installed.  Basically, you need a web server with PHP support and a MySQL/MariaDB database server.

The various web applications are spread out between Jason's [minorGems](https://github.com/jasonrohrer/minorGems/tree/master/game) and [OneLife](https://github.com/jasonrohrer/OneLife) projects.

***OneLife***
* reflector (This is the web service that controls load balancing/etc. as seen [here](http://onehouronelife.com/reflector/server.php?action=report).)
* photoServer
* lineageServer
* curseServer
* lifeTokenServer

***minorGems***
* ticketServer
* reviewServer
* mailingList
* bulkEmailer
* steamGate

Having some experience with web servers helps here, but the basics would be to copy the folders for the web service(s) you want to run and paste them into the root folder of your web server setup.  Where applicable, a settings.php file will be inside most of these folders that you'll need to edit to change the database connection string to match your MySQL/MariaDB setup.  And unless you have a YubiKey, you'll also want to disable those options:
```
$enableYubikey = 0;
```
I would **highly** encourage you to read through the settings.php file(s), as well as the protocol.txt file within each of the folders, as these have better details as to the available/expected functions and can help you get a clearer understanding of how they're designed to operate.

Assuming that you've got everything properly setup (web server, PHP, database server), you should then be able to navigate to the index.php or server.php file(s) in order for them to create the necessary database table structures and then utilize its service.  If you've read through the settings mentioned previously, you'll then need to use the access password(s) to login and manage your service(s).  The default password, if you didn't change it, is:  *secret*

That should be it!  You should now be able to utilize whatever web services that you want in your own customized/private setup.  If you want to start using them, you'll have to edit your client's config settings to point to your private web service instead of Jason's official one(s.)  I hope this helps you on your future adventures, whatever they may be!

**Comment by Awbz** [comment]
It should also be noted that this assumes an Ubuntu-style setup and using an Apache or nginx web server.  The same setup could also be accomplished on a Windows-based IIS web server, but I'll have to leave getting IIS with PHP properly installed up to you.

**Comment by Adrinus** [comment]
Wow! That should be plenty of info for me to figure it out! Thanks a ton!

I dunno if it's possible, but you might want to link the above somewhere for any others who are interested. 

Anyhow, that fixes my issue, thanks again!
