### ISSUE TITLE
Issue with Homemarker

### ISSUE THREAD

**Issue by Glaise5** [Awbz/OneLife#99]
The homemarker is sending me to the wilderness and I can not find bell because it sends me either at home or the wilderness and I would like to see the bell so when I get older I can go to bell if it is close. and I can replace it to home and cut the homemarker but still does not show bell. I would really Thank You if someone can fix it.

**Comment by Awbz** [comment]
Apologies for the late response on this issue.  For whatever reason, I failed to see it for all of these months!  Could you elaborate a bit more on what the issue seems to be?  Admittedly, the game has changed so much since this initial post that it's likely no longer an issue...

Thanks to taidg, home markers got an overhaul a few months ago (#85) in this mod.  This may, or may not, help with your issue.  But if you have multiple home markers, you can cycle between them with the + key until you find whatever bell you're looking for.

Alternatively, the [hetuw](https://github.com/hetuw/OneLife) mod has more robust features when it comes to coordinates & locations.  So if you still have issues with the default-style home markers, you could always try giving that modded client a shot and see if it meets your needs!
